### ISSUE TITLE
New, Backup Release

### ISSUE THREAD

**Issue by bzmshang** [LeslieLeung/reaper#12]
Is it possible to add a feature that backs up all the release files in the repository

**Comment by LeslieLeung** [comment]
Yes. Do you want to backup all of the releases at once or backup only the latest release in cron?

**Comment by LeslieLeung** [comment]
Archiving all release assets is now available through `bury` command. You can check it out [here](https://github.com/LeslieLeung/reaper?tab=readme-ov-file#bury) with the latest release. @bzmshang
